Repository apeun-gidaechi/seugi-android, pull requests merged in 2024-10, with the labels that each got.

#273 Feature/Create Google Login
  .github/workflows/ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/seugi/util/FirebaseMessageService.kt
  build.gradle.kts
  data/core/build.gradle.kts
  data/core/src/main/java/com/seugi/data/core/mapper/TokenMapper.kt
  data/core/src/main/java/com/seugi/data/core/model/TokenModel.kt
  data/firebase-token/.gitignore
  data/firebase-token/build.gradle.kts
  data/firebase-token/src/main/java/com/seugi/data/firebasetoken/FirebaseTokenRepository.kt
  data/firebase-token/src/main/java/com/seugi/data/firebasetoken/di/RepositoryModule.kt
  data/firebase-token/src/main/java/com/seugi/data/firebasetoken/mapper/FirebaseTokenMapper.kt
  data/firebase-token/src/main/java/com/seugi/data/firebasetoken/model/FirebaseTokenModel.kt
  data/firebase-token/src/main/java/com/seugi/data/firebasetoken/repository/FirebaseTokenRepositoryImpl.kt
  data/member/build.gradle.kts
  data/member/src/main/java/com/seugi/data/member/MemberRepository.kt
  data/member/src/main/java/com/seugi/data/member/mapper/EmailSignInMapper.kt
  data/member/src/main/java/com/seugi/data/member/model/EmailSignInModel.kt
  data/member/src/main/java/com/seugi/data/member/repository/MemberRepositoryImpl.kt
  data/oauth/.gitignore
  data/oauth/build.gradle.kts
  data/oauth/src/main/java/com/seugi/data/oauth/OauthRepository.kt
  data/oauth/src/main/java/com/seugi/data/oauth/di/OauthRepositoryModule.kt
  data/oauth/src/main/java/com/seugi/data/oauth/repository/OauthRepositoryImpl.kt
  data/token/build.gradle.kts
  data/token/src/main/java/com/seugi/data/token/TokenRepository.kt
  data/token/src/main/java/com/seugi/data/token/mapper/TokenMapper.kt
  data/token/src/main/java/com/seugi/data/token/repository/TokenRepositoryImpl.kt
  feature-onboarding/join/build.gradle.kts
  feature-onboarding/join/src/main/java/com/seugi/join/feature/OAuthSignUpScreen.kt
  feature-onboarding/login/build.gradle.kts
  feature-onboarding/login/src/main/java/com/seugi/login/EmailSignInScreen.kt
  feature-onboarding/login/src/main/java/com/seugi/login/EmailSignInViewModel.kt
  feature-onboarding/onboarding/src/main/java/com/seugi/onboarding/OnboardingScreen.kt
  feature-onboarding/start/build.gradle.kts
  feature-onboarding/start/src/main/java/com/seugi/start/StartScreen.kt
  feature-onboarding/start/src/main/java/com/seugi/start/StartViewModel.kt
  feature-onboarding/start/src/main/java/com/seugi/start/model/StartUiState.kt
  feature-onboarding/start/src/main/java/com/seugi/start/navigation/StartNavigation.kt
  feature-onboarding/start/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  local/room/src/main/java/com/seugi/local/room/SeugiDatabase.kt
  local/room/src/main/java/com/seugi/local/room/dao/FirebaseTokenDao.kt
  local/room/src/main/java/com/seugi/local/room/di/SeugiDaoModule.kt
  local/room/src/main/java/com/seugi/local/room/model/FirebaseTokenEntity.kt
  local/room/src/main/java/com/seugi/local/room/util/SeugiTable.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
  network/core/src/main/java/com/seugi/network/core/response/TokenResponse.kt
  network/oauth/.gitignore
  network/oauth/build.gradle.kts
  network/oauth/src/main/java/com/seugi/network/oauth/OauthDatasource.kt
  network/oauth/src/main/java/com/seugi/network/oauth/datasource/OauthDatasourceImpl.kt
  network/oauth/src/main/java/com/seugi/network/oauth/di/OauthDatasourceModule.kt
  network/oauth/src/main/java/com/seugi/network/oauth/request/OauthRequest.kt
  network/sign-in/src/main/java/com/seugi/network/MemberDatasource.kt
  network/sign-in/src/main/java/com/seugi/network/datasource/MemberDatasourceImpl.kt
  network/sign-in/src/main/java/com/seugi/network/request/EmailSignInRequest.kt
  settings.gradle.kts
Labels: Feature

#274 Refactor/bottom navigation visible
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/navigation/ChatDetailNavigation.kt
  feature-main/chat-seugi/src/main/java/com/seugi/chatseugi/ChatSeugiScreen.kt
  feature-main/chat-seugi/src/main/java/com/seugi/chatseugi/navigation/ChatSeugiNavigation.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/card/SchoolCard.kt
  feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/notification-create/src/main/java/com/seugi/notificationcreate/NotificationCreateScreen.kt
  feature-main/notification-create/src/main/java/com/seugi/notificationcreate/navigation/NotificationCreateNavigation.kt
  feature-main/notification-edit/src/main/java/com/seugi/notificationedit/NotificationEditScreen.kt
  feature-main/notification-edit/src/main/java/com/seugi/notificationedit/navigation/NotificationEditNavigation.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateScreen.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/navigation/RoomCreateNavigation.kt
  feature-main/setting/src/main/java/com/seugi/setting/SettingScreen.kt
  feature-main/setting/src/main/java/com/seugi/setting/navigate/SettingNavigate.kt
Labels: Refactor

#278 Refactor/Main ViewModel Logic
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
  feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
  feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
  feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
Labels: Refactor

#279 Feature/Create Meal Widget
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/meal_widget_info.xml
  common/build.gradle.kts
  common/src/main/java/com/seugi/common/utiles/Utiles.kt
  data/meal/build.gradle.kts
  data/meal/src/main/java/com/seugi/data/meal/response/MealModel.kt
  data/meal/src/main/java/com/seugi/data/meal/response/MealType.kt
  feature-main/meal-widget/.gitignore
  feature-main/meal-widget/build.gradle.kts
  feature-main/meal-widget/consumer-rules.pro
  feature-main/meal-widget/proguard-rules.pro
  feature-main/meal-widget/src/main/java/com/seugi/meal/widget/MealWidget.kt
  feature-main/meal-widget/src/main/java/com/seugi/meal/widget/component/MealListProvider.kt
  feature-main/meal-widget/src/main/java/com/seugi/meal/widget/definition/MealWidgetStateDefinition.kt
  feature-main/meal-widget/src/main/java/com/seugi/meal/widget/di/MealWidgetEntryPoint.kt
  feature-main/meal-widget/src/main/java/com/seugi/meal/widget/di/WidgetModule.kt
  feature-main/meal-widget/src/main/java/com/seugi/meal/widget/model/MealWidgetState.kt
  feature-main/meal-widget/src/main/res/drawable/shape100_primary050.xml
  feature-main/meal-widget/src/main/res/drawable/shape18_white.xml
  feature-main/meal-widget/src/main/res/drawable/shape22_neutral.xml
  feature-main/meal-widget/src/main/res/layout/item_meal_menu.xml
  feature-main/meal-widget/src/main/res/layout/widget_meal_layout.xml
  feature-main/meal-widget/src/main/res/values/styles.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: Feature

#280 Feature/Reflect New Chat Logic
  common/src/main/java/com/seugi/common/utiles/Extension.kt
  data/core/src/main/java/com/seugi/data/core/mapper/ChatRoomMapper.kt
  data/core/src/main/java/com/seugi/data/core/mapper/UserMapper.kt
  data/core/src/main/java/com/seugi/data/core/model/ChatRoomModel.kt
  data/core/src/main/java/com/seugi/data/core/model/UserInfoModel.kt
  data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
  data/message/src/main/java/com/seugi/data/message/mapper/MessageStompMapper.kt
  data/message/src/main/java/com/seugi/data/message/model/MessageRoomEvent.kt
  data/message/src/main/java/com/seugi/data/message/model/stomp/MessageStompLifecycleModel.kt
  designsystem/src/main/java/com/seugi/designsystem/component/Avatar.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/model/ChatDetailUiState.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
  network/core/src/main/java/com/seugi/network/core/response/ChatRoomResponse.kt
  network/core/src/main/java/com/seugi/network/core/response/UserInfoResponse.kt
  network/core/src/main/java/com/seugi/network/core/utiles/LocalDateTimeTypeAdapter.kt
  network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
  network/message/src/main/java/com/seugi/network/message/response/MessageRoomEventResponse.kt
  network/message/src/main/java/com/seugi/network/message/response/stomp/MessageStompLifecycleResponse.kt
  stomp-client/src/main/java/com/seugi/stompclient/provider/AbstractConnectionProvider.java
  stomp-client/src/main/java/com/seugi/stompclient/provider/OkHttpConnectionProvider.java
Labels: Feature

#282 Feature/Profile Load Logic
  data/token/src/main/java/com/seugi/data/token/repository/TokenRepositoryImpl.kt
  data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
  data/workspace/src/main/java/com/seugi/data/workspace/mapper/WorkspaceMapper.kt
  data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
  feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
  feature-main/meal-widget/src/main/java/com/seugi/meal/widget/MealWidget.kt
  feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceDetailNavigation.kt
  local/room/build.gradle.kts
  local/room/src/main/java/com/seugi/local/room/SeugiDatabase.kt
  local/room/src/main/java/com/seugi/local/room/dao/WorkspaceDao.kt
  local/room/src/main/java/com/seugi/local/room/model/WorkspaceEntity.kt
  local/room/src/main/java/com/seugi/local/room/util/LongListTypeConverter.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
  network/sign-in/src/main/java/com/seugi/network/datasource/MemberDatasourceImpl.kt
  network/token/build.gradle.kts
  network/token/src/main/java/com/seugi/network/token/TokenDatasource.kt
  network/token/src/main/java/com/seugi/network/token/datasource/TokenDatasourceImpl.kt
Labels: Feature

#284 Feature/Schedule Remote
  data/schedule/build.gradle.kts
  data/schedule/consumer-rules.pro
  data/schedule/proguard-rules.pro
  data/schedule/src/main/java/com/seugi/data/schedule/ScheduleRepository.kt
  data/schedule/src/main/java/com/seugi/data/schedule/di/ScheduleRepositoryModule.kt
  data/schedule/src/main/java/com/seugi/data/schedule/mapper/ScheduleMapper.kt
  data/schedule/src/main/java/com/seugi/data/schedule/model/ScheduleModel.kt
  data/schedule/src/main/java/com/seugi/data/schedule/repository/ScheduleRepositoryImpl.kt
  designsystem/src/main/res/drawable/ic_emoji_happy.png
  designsystem/src/main/res/drawable/ic_emoji_happy.xml
  designsystem/src/main/res/drawable/ic_emoji_mouth.png
  designsystem/src/main/res/drawable/ic_emoji_mouth.xml
  designsystem/src/main/res/drawable/ic_emoji_sad.png
  designsystem/src/main/res/drawable/ic_emoji_sad.xml
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-seugi/src/main/java/com/seugi/chatseugi/ChatSeugiScreen.kt
  feature-main/home/build.gradle.kts
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/card/ScheduleCard.kt
  feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
  feature-main/setting/src/main/java/com/seugi/setting/SettingScreen.kt
  feature-main/workspace-create/src/main/java/com/seugi/workspacecreate/WorkspaceCreateScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/SelectingJobScreen.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/WaitingJoinScreen.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/joinsuccess/JoinSuccessScreen.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/schoolcode/SchoolCodeScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/EmailSignUpScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/OAuthSignUpScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/emailverification/EmailVerificationScreen.kt
  feature-onboarding/login/src/main/java/com/seugi/login/EmailSignInScreen.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/schedule/build.gradle.kts
  network/schedule/consumer-rules.pro
  network/schedule/proguard-rules.pro
  network/schedule/src/main/java/com/seugi/network/schedule/ScheduleDataSource.kt
  network/schedule/src/main/java/com/seugi/network/schedule/datasource/ScheduleDataSourceImpl.kt
  network/schedule/src/main/java/com/seugi/network/schedule/di/DataSourceModule.kt
  network/schedule/src/main/java/com/seugi/network/schedule/response/ScheduleResponse.kt
  settings.gradle.kts
Labels: Feature

#286 Relese/0.0.1
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: Deploy

#290 Feature/Timetable Widget
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/timetable_widget_info.xml
  data/timetable/src/main/java/com/seugi/data/timetable/mapper/TimetableMapper.kt
  data/timetable/src/main/java/com/seugi/data/timetable/model/TimetableModel.kt
  feature-main/timetable-widget/build.gradle.kts
  feature-main/timetable-widget/src/main/java/com/seugi/timetable/widget/TimetableWidget.kt
  feature-main/timetable-widget/src/main/java/com/seugi/timetable/widget/component/TimetableListProvider.kt
  feature-main/timetable-widget/src/main/java/com/seugi/timetable/widget/di/TimetableWidgetEntryPoint.kt
  feature-main/timetable-widget/src/main/java/com/seugi/timetable/widget/di/WidgetModule.kt
  feature-main/timetable-widget/src/main/res/drawable/shape100_primary050.xml
  feature-main/timetable-widget/src/main/res/drawable/shape18_white.xml
  feature-main/timetable-widget/src/main/res/drawable/shape22_neutral.xml
  feature-main/timetable-widget/src/main/res/layout/item_meal_menu.xml
  feature-main/timetable-widget/src/main/res/layout/widget_timetable_layout.xml
  feature-main/timetable-widget/src/main/res/values/strings.xml
  feature-main/timetable-widget/src/main/res/values/styles.xml
  gradle/libs.versions.toml
  network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
  network/core/src/main/java/com/seugi/network/core/response/FakeLocalDateResponse.kt
  network/core/src/main/java/com/seugi/network/core/utiles/FakeLocalDateResponseTypeAdapter.kt
  network/timetable/build.gradle.kts
  network/timetable/src/androidTest/java/com/seugi/network/timetable/TimetableDataSourceTest.kt
  settings.gradle.kts
Labels: Feature

#292 Feature/Create Setting Feature
  data/member/src/main/java/com/seugi/data/member/MemberRepository.kt
  data/member/src/main/java/com/seugi/data/member/repository/MemberRepositoryImpl.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/FirstScreen.kt
  feature-main/setting/build.gradle.kts
  feature-main/setting/src/main/java/com/seugi/setting/SettingScreen.kt
  feature-main/setting/src/main/java/com/seugi/setting/SettingViewModel.kt
  feature-main/setting/src/main/java/com/seugi/setting/model/SettingSideEffect.kt
  feature-main/setting/src/main/java/com/seugi/setting/navigate/SettingNavigate.kt
  feature-main/workspace-create/src/main/java/com/seugi/workspacecreate/WorkspaceCreateScreen.kt
  feature-main/workspace-create/src/main/java/com/seugi/workspacecreate/WorkspaceCreateViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/sign-in/src/main/java/com/seugi/network/MemberDatasource.kt
  network/sign-in/src/main/java/com/seugi/network/datasource/MemberDatasourceImpl.kt
  network/sign-in/src/main/java/com/seugi/network/request/EditRequest.kt
Labels: Feature

#293 Feature/Chat Pagination
  data/core/src/main/java/com/seugi/data/core/mapper/UserMapper.kt
  data/message/src/main/java/com/seugi/data/message/MessageRepository.kt
  data/message/src/main/java/com/seugi/data/message/repository/MessageRepositoryImpl.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  network/message/src/main/java/com/seugi/network/message/MessageDataSource.kt
  network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
Labels: Feature

#295 Refactor/User Name And Nick
  data/core/src/main/java/com/seugi/data/core/model/ProfileModel.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateViewModel.kt
Labels: Refactor

#297 Fix/Start Button Unresponsive
  feature-onboarding/start/src/main/java/com/seugi/start/StartScreen.kt
Labels: Bug

#299 Fix/Bounce Click Scale Error
  designsystem/src/main/java/com/seugi/designsystem/animation/ButtonClick.kt
  designsystem/src/main/java/com/seugi/designsystem/component/Category.kt
  designsystem/src/main/java/com/seugi/designsystem/component/Dialog.kt
  designsystem/src/main/java/com/seugi/designsystem/component/ListItem.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/card/MealCard.kt
  feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
Labels: Bug

#301 Feature/Add Navigation Personal Chat
  feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
  feature-main/chat/src/main/java/com/seugi/chat/navigation/ChatNavigation.kt
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
Labels: Feature

#303 Feature/Reflect Room Remote Image
  feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
  feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
Labels: Feature

#306 Feature/Add Notification Emoji Spacing
  feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
  feature-main/notification/src/main/java/com/seugi/notification/NotificationViewModel.kt
Labels: Feature

#308 Fix/Schedule Load Error
  data/schedule/src/main/java/com/seugi/data/schedule/mapper/ScheduleMapper.kt
  network/schedule/src/main/java/com/seugi/network/schedule/response/ScheduleResponse.kt
Labels: Bug

#310 Feature/Create Re Load Workspace
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
Labels: Feature

#312 Fix/Date ISO Format
  data/meal/src/main/java/com/seugi/data/meal/mapper/MealMapper.kt
  data/meal/src/main/java/com/seugi/data/meal/repository/MealRepositoryImpl.kt
  data/schedule/src/main/java/com/seugi/data/schedule/mapper/ScheduleMapper.kt
  data/timetable/src/main/java/com/seugi/data/timetable/mapper/TimetableMapper.kt
  network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
  network/core/src/main/java/com/seugi/network/core/utiles/KotlinLocalDateTypeAdapter.kt
  network/meal/src/main/java/com/seugi/network/meal/MealDataSource.kt
  network/meal/src/main/java/com/seugi/network/meal/datasource/MealDataSourceImpl.kt
  network/meal/src/main/java/com/seugi/network/meal/response/MealResponse.kt
  network/schedule/src/main/java/com/seugi/network/schedule/response/ScheduleResponse.kt
  network/timetable/src/main/java/com/seugi/network/timetable/response/TimetableResponse.kt
Labels: Bug

#315 Fix/Chat Name Height Maximum
  designsystem/src/main/java/com/seugi/designsystem/component/chat/ChatList.kt
Labels: Feature

#317 Feature/Change Emoji Bottom Sheet
  feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
  gradle/libs.versions.toml
Labels: Feature

#318 Feature/Chat Detail Search
  designsystem/src/main/java/com/seugi/designsystem/component/TopBar.kt
  designsystem/src/main/java/com/seugi/designsystem/component/chat/ChatItem.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
Labels: Feature

#320 Feature/Member Loading Shimmer
  designsystem/src/main/java/com/seugi/designsystem/component/ShimmerEffect.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateViewModel.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/model/RoomCreateUiState.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/FirstScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/model/WorkspaceMemberUiState.kt
  ui/src/main/java/com/seugi/ui/component/SeugiMemberListLoading.kt
Labels: Feature

#322 Feature/Create Invite Member Feature
  data/core/src/main/java/com/seugi/data/core/mapper/UserMapper.kt
  data/core/src/main/java/com/seugi/data/core/model/ChatRoomModel.kt
  data/core/src/main/java/com/seugi/data/core/model/UserModel.kt
  data/group-chat/src/main/java/com/seugi/data/groupchat/GroupChatRepository.kt
  data/group-chat/src/main/java/com/seugi/data/groupchat/repository/GroupChatRepositoryImpl.kt
  data/message/src/main/java/com/seugi/data/message/MessageRepository.kt
  data/message/src/main/java/com/seugi/data/message/mapper/MessageLoadMapper.kt
  data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
  data/message/src/main/java/com/seugi/data/message/model/MessageRoomEvent.kt
  data/message/src/main/java/com/seugi/data/message/repository/MessageRepositoryImpl.kt
  data/notification/src/main/java/com/seugi/data/notification/model/NotificationModel.kt
  data/perosnal-chat/src/main/java/com/seugi/data/personalchat/PersonalChatRepository.kt
  data/perosnal-chat/src/main/java/com/seugi/data/personalchat/repository/PersonalChatRepositoryImpl.kt
  data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
  data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
  designsystem/src/main/java/com/seugi/designsystem/component/Button.kt
  designsystem/src/main/java/com/seugi/designsystem/component/Dialog.kt
  designsystem/src/main/res/drawable/ic_copy_line.xml
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/model/ChatDetailUiState.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/navigation/ChatDetailNavigation.kt
  feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
  feature-main/chat/src/main/java/com/seugi/chat/navigation/ChatNavigation.kt
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
  feature-main/notification-edit/src/main/java/com/seugi/notificationedit/NotificationEditScreen.kt
  feature-main/notification-edit/src/main/java/com/seugi/notificationedit/navigation/NotificationEditNavigation.kt
  feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
  feature-main/notification/src/main/java/com/seugi/notification/navigation/NotificationNavigation.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateScreen.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateViewModel.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/model/RoomCreateUiState.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/navigation/RoomCreateNavigation.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/FirstScreen.kt
  feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
  feature-main/room/src/main/java/com/seugi/room/navigation/RoomNavigation.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/invitemember/InviteMemberScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/invitemember/InviteMemberViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/invitemember/model/DialogModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/invitemember/model/WaitMemberUiState.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/InviteMemberNavigation.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceDetailNavigation.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/core/src/main/java/com/seugi/network/core/response/ChatRoomResponse.kt
  network/core/src/main/java/com/seugi/network/core/response/UserResponse.kt
  network/group-chat/src/main/java/com/seugi/network/groupchat/GroupChatDataSource.kt
  network/group-chat/src/main/java/com/seugi/network/groupchat/datasource/GroupChatDataSourceImpl.kt
  network/group-chat/src/main/java/com/seugi/network/groupchat/request/GroupChatCreateRequest.kt
  network/message/src/main/java/com/seugi/network/message/response/MessageRoomEventResponse.kt
  network/notification/src/main/java/com/seugi/network/notification/response/NotificationResponse.kt
  network/personal-chat/src/main/java/com/seugi/network/personalchat/PersonalChatDataSource.kt
  network/personal-chat/src/main/java/com/seugi/network/personalchat/datasource/PersonalChatDataSourceImpl.kt
  network/personal-chat/src/main/java/com/seugi/network/personalchat/request/PersonalChatCreateRequest.kt
  network/workspace/src/main/java/com/seugi/network/workspace/WorkspaceDataSource.kt
  network/workspace/src/main/java/com/seugi/network/workspace/datasource/WorkspaceDataSourceImpl.kt
  network/workspace/src/main/java/com/seugi/network/workspace/request/InviteMemberRequest.kt
Labels: Feature

#325 Feature/Edit Profile Feature
  feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
  feature-main/setting/src/main/java/com/seugi/setting/SettingScreen.kt
  feature-main/setting/src/main/java/com/seugi/setting/SettingViewModel.kt
Labels: Feature

#328 Feature/Remove Apple Login Button
  feature-onboarding/start/src/main/java/com/seugi/start/StartScreen.kt
Labels: Feature

#329 Feature/Ai Response
  data/core/build.gradle.kts
  data/core/src/main/java/com/seugi/data/core/mapper/MealMapper.kt
  data/core/src/main/java/com/seugi/data/core/mapper/NotificationMapper.kt
  data/core/src/main/java/com/seugi/data/core/model/MealModel.kt
  data/core/src/main/java/com/seugi/data/core/model/MealType.kt
  data/core/src/main/java/com/seugi/data/core/model/NotificationEmojiModel.kt
  data/core/src/main/java/com/seugi/data/core/model/NotificationModel.kt
  data/core/src/main/java/com/seugi/data/core/model/TimetableModel.kt
  data/meal/build.gradle.kts
  data/meal/src/main/java/com/seugi/data/meal/MealRepository.kt
  data/meal/src/main/java/com/seugi/data/meal/mapper/MealMapper.kt
  data/meal/src/main/java/com/seugi/data/meal/repository/MealRepositoryImpl.kt
  data/message/build.gradle.kts
  data/message/src/main/java/com/seugi/data/message/MessageRepository.kt
  data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
  data/message/src/main/java/com/seugi/data/message/model/MessageBotRawKeyword.kt
  data/message/src/main/java/com/seugi/data/message/model/MessageRoomEvent.kt
  data/message/src/main/java/com/seugi/data/message/repository/MessageRepositoryImpl.kt
  data/notification/src/main/java/com/seugi/data/notification/NotificationRepository.kt
  data/notification/src/main/java/com/seugi/data/notification/repository/NotificationRepositoryImpl.kt
  data/timetable/src/main/java/com/seugi/data/timetable/TimetableRepository.kt
  data/timetable/src/main/java/com/seugi/data/timetable/mapper/TimetableMapper.kt
  data/timetable/src/main/java/com/seugi/data/timetable/repository/TimetableRepositoryImpl.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/model/ChatLocalType.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
  feature-main/meal-widget/src/main/java/com/seugi/meal/widget/MealWidget.kt
  feature-main/meal-widget/src/main/java/com/seugi/meal/widget/model/MealWidgetState.kt
  feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
  feature-main/notification/src/main/java/com/seugi/notification/NotificationViewModel.kt
  feature-main/notification/src/main/java/com/seugi/notification/model/NotificationUiState.kt
  feature-main/timetable-widget/src/main/java/com/seugi/timetable/widget/TimetableWidget.kt
  network/core/src/main/java/com/seugi/network/core/utiles/Extension.kt
  network/core/src/main/java/com/seugi/network/core/utiles/ImmutableListTypeAdapter.kt
  network/core/src/main/java/com/seugi/network/core/utiles/LocalDateTimeTypeAdapter.kt
  network/message/src/main/java/com/seugi/network/message/MessageDataSource.kt
  network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
  network/message/src/main/java/com/seugi/network/message/request/MessageRequest.kt
Labels: Feature

#336 Feature/Timetable Screen
  data/core/src/main/java/com/seugi/data/core/model/TimetableModel.kt
  data/timetable/src/main/java/com/seugi/data/timetable/TimetableRepository.kt
  data/timetable/src/main/java/com/seugi/data/timetable/mapper/TimetableMapper.kt
  data/timetable/src/main/java/com/seugi/data/timetable/repository/TimetableRepositoryImpl.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/timetable/build.gradle.kts
  feature-main/timetable/src/main/java/com/seugi/timetable/TimetableScreen.kt
  feature-main/timetable/src/main/java/com/seugi/timetable/TimetableViewModel.kt
  feature-main/timetable/src/main/java/com/seugi/timetable/navigation/TimetableNavigation.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/timetable/src/main/java/com/seugi/network/timetable/TimetableDataSource.kt
  network/timetable/src/main/java/com/seugi/network/timetable/datasource/TimetableDataSourceImpl.kt
  settings.gradle.kts
Labels: Feature

#331 Feature/Chat User Invite
  common/src/main/java/com/seugi/common/utiles/Extension.kt
  data/group-chat/src/main/java/com/seugi/data/groupchat/GroupChatRepository.kt
  data/group-chat/src/main/java/com/seugi/data/groupchat/repository/GroupChatRepositoryImpl.kt
  feature-main/chat-datail/build.gradle.kts
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/model/ChatDetailUiState.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailInviteScreen.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/group-chat/src/main/java/com/seugi/network/groupchat/GroupChatDataSource.kt
  network/group-chat/src/main/java/com/seugi/network/groupchat/datasource/GroupChatDataSourceImpl.kt
  network/group-chat/src/main/java/com/seugi/network/groupchat/request/GroupChatMemberAddRequest.kt
Labels: Feature

#334 Feature/Task Feature
  data/task/build.gradle.kts
  data/task/consumer-rules.pro
  data/task/proguard-rules.pro
  data/task/src/main/java/com/seugi/data/task/TaskRepository.kt
  data/task/src/main/java/com/seugi/data/task/di/RepositoryModule.kt
  data/task/src/main/java/com/seugi/data/task/mapper/TaskMapper.kt
  data/task/src/main/java/com/seugi/data/task/model/TaskModel.kt
  data/task/src/main/java/com/seugi/data/task/model/TaskType.kt
  data/task/src/main/java/com/seugi/data/task/repository/TaskRepositoryImpl.kt
  designsystem/src/main/java/com/seugi/designsystem/component/textfield/TextField.kt
  feature-main/home/build.gradle.kts
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/card/ScheduleCard.kt
  feature-main/home/src/main/java/com/seugi/home/card/TaskCard.kt
  feature-main/home/src/main/java/com/seugi/home/card/TimeScheduleCard.kt
  feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
  feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/task-create/build.gradle.kts
  feature-main/task-create/src/main/java/com/seugi/task/create/TaskCreateScreen.kt
  feature-main/task-create/src/main/java/com/seugi/task/create/TaskCreateViewModel.kt
  feature-main/task-create/src/main/java/com/seugi/task/create/model/TaskCreateSideEffect.kt
  feature-main/task-create/src/main/java/com/seugi/task/create/navigation/TaskCreateNavigation.kt
  feature-main/task/build.gradle.kts
  feature-main/task/src/main/java/com/seugi/task/TaskScreen.kt
  feature-main/task/src/main/java/com/seugi/task/TaskViewModel.kt
  feature-main/task/src/main/java/com/seugi/task/model/TaskUiState.kt
  feature-main/task/src/main/java/com/seugi/task/navigation/TaskNavigation.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
  feature-onboarding/start/src/main/java/com/seugi/start/StartScreen.kt
  feature-onboarding/start/src/main/res/values/strings.xml
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/task/build.gradle.kts
  network/task/src/main/java/com/seugi/network/task/TaskDataSource.kt
  network/task/src/main/java/com/seugi/network/task/datasource/TaskDataSourceImpl.kt
  network/task/src/main/java/com/seugi/network/task/di/DataSourceModule.kt
  network/task/src/main/java/com/seugi/network/task/request/TaskCreateRequest.kt
  network/task/src/main/java/com/seugi/network/task/response/TaskGoogleResponse.kt
  network/task/src/main/java/com/seugi/network/task/response/TaskResponse.kt
  settings.gradle.kts
Labels: Feature

#339 Refactor/Edit Seugi
  data/core/build.gradle.kts
  data/core/src/main/java/com/seugi/data/core/mapper/TimetableMapper.kt
  data/message/build.gradle.kts
  data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
  data/timetable/src/main/java/com/seugi/data/timetable/repository/TimetableRepositoryImpl.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/card/MealCard.kt
  feature-main/home/src/main/java/com/seugi/home/card/ScheduleCard.kt
  network/catseugi/src/main/java/com/seugi/network/catseugi/datasource/CatSeugiDataSourceImpl.kt
  network/catseugi/src/main/java/com/seugi/network/catseugi/request/CatSeugiRequest.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
Labels: Refactor

#342 Feature/Create Firebase Cloud Message
  app/build.gradle.kts
  app/src/main/java/com/seugi/MainActivity.kt
  app/src/main/java/com/seugi/util/FirebaseMessageService.kt
  app/src/main/res/values/strings.xml
  designsystem/src/main/java/com/seugi/designsystem/component/Dialog.kt
  gradle/libs.versions.toml
Labels: Feature

#343 Feature/Meal Screen
  data/meal/src/main/java/com/seugi/data/meal/MealRepository.kt
  data/meal/src/main/java/com/seugi/data/meal/repository/MealRepositoryImpl.kt
  designsystem/src/main/java/com/seugi/designsystem/component/DatePicker.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/card/MealCard.kt
  feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/meal/build.gradle.kts
  feature-main/meal/src/main/java/com/seugi/meal/MealScreen.kt
  feature-main/meal/src/main/java/com/seugi/meal/MealViewModel.kt
  feature-main/meal/src/main/java/com/seugi/meal/model/MealUiState.kt
  feature-main/meal/src/main/java/com/seugi/meal/navigation/MealNavigation.kt
  local/room/src/main/java/com/seugi/local/room/dao/MealDao.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/meal/src/main/java/com/seugi/network/meal/MealDataSource.kt
  network/meal/src/main/java/com/seugi/network/meal/datasource/MealDataSourceImpl.kt
  settings.gradle.kts
Labels: Feature

#345 Feature/Chat Deatil Ai Response Model to String
  data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
  data/message/src/main/java/com/seugi/data/message/model/MessageRoomEvent.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
Labels: Feature

#346 Feature/Apply Ai Mapping
  data/message/src/main/java/com/seugi/data/message/MessageRepository.kt
  data/message/src/main/java/com/seugi/data/message/mapper/CatSeugiMapper.kt
  data/message/src/main/java/com/seugi/data/message/model/CatSeugiResponse.kt
  data/message/src/main/java/com/seugi/data/message/repository/MessageRepositoryImpl.kt
  feature-main/chat-seugi/src/main/java/com/seugi/chatseugi/ChatSeugiViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/card/CatSeugiCard.kt
  network/message/src/main/java/com/seugi/network/message/MessageDataSource.kt
  network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
  network/message/src/main/java/com/seugi/network/message/request/CatSeugiRequest.kt
  network/message/src/main/java/com/seugi/network/message/response/CatSeugiResponse.kt
Labels: Feature

#348 Fix/Not Decrease Read Count
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/screen/ChatDetailChatScreen.kt
Labels: Bug

#350 Feature/Edit Task Infinity Date Notation
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/card/TaskCard.kt
  feature-main/task/src/main/java/com/seugi/task/TaskScreen.kt
Labels: Feature
