Repository apeun-gidaechi/seugi-android, pull requests merged in 2024-09, with the labels that each got.

#229 Fix/Load Workspace Id Bug
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
Labels: Bug

#232 Feature/Create Load Local Id
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceDetailNavigation.kt
Labels: Feature

#234 Feature/Create Room Member Filter
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateScreen.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/RoomCreateViewModel.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/navigation/RoomCreateNavigation.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/FirstScreen.kt
  feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
  feature-main/room/src/main/java/com/seugi/room/navigation/RoomNavigation.kt
Labels: Feature

#237 Fix/Chat Detail Bug
  data/message/src/main/java/com/seugi/data/message/mapper/MessageStompMapper.kt
  data/message/src/main/java/com/seugi/data/message/model/stomp/MessageStompLifecycleModel.kt
  feature-main/chat-datail/build.gradle.kts
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
  network/group-chat/src/main/java/com/seugi/network/groupchat/datasource/GroupChatDataSourceImpl.kt
  network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
  network/message/src/main/java/com/seugi/network/message/request/MessageRequest.kt
  network/message/src/main/java/com/seugi/network/message/response/stomp/MessageStompLifecycleResponse.kt
  network/personal-chat/src/main/java/com/apeun/gidaechi/data/personalchat/datasource/PersonalChatDataSourceImpl.kt
  stomp-client/src/main/java/com/seugi/stompclient/StompClient.java
  stomp-client/src/main/java/com/seugi/stompclient/dto/LifecycleEvent.java
  stomp-client/src/main/java/com/seugi/stompclient/provider/AbstractConnectionProvider.java
  stomp-client/src/main/java/com/seugi/stompclient/provider/OkHttpConnectionProvider.java
  stomp-client/src/main/java/com/seugi/stompclient/provider/WebSocketsConnectionProvider.java
Labels: Feature

#238 Feature/Create Cho Fast Workspace Load
  feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
Labels: Feature

#240 Feature/Move Profile Data
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
  feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
  feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
  feature-main/profile/src/main/java/com/seugi/profile/ProfileViewModel.kt
  feature-main/profile/src/main/java/com/seugi/profile/navigation/ProfileNavigation.kt
Labels: Feature

#242 Feature/Timetable Remote Feature
  data/timetable/build.gradle.kts
  data/timetable/consumer-rules.pro
  data/timetable/proguard-rules.pro
  data/timetable/src/main/java/com/seugi/data/timetable/TimetableRepository.kt
  data/timetable/src/main/java/com/seugi/data/timetable/di/RepositoryModule.kt
  data/timetable/src/main/java/com/seugi/data/timetable/mapper/TimetableMapper.kt
  data/timetable/src/main/java/com/seugi/data/timetable/model/TimetableModel.kt
  data/timetable/src/main/java/com/seugi/data/timetable/repository/TimetableRepositoryImpl.kt
  feature-main/home/build.gradle.kts
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/timetable/build.gradle.kts
  network/timetable/src/main/java/com/seugi/network/timetable/TimetableDataSource.kt
  network/timetable/src/main/java/com/seugi/network/timetable/datasource/TimetableDataSourceImpl.kt
  network/timetable/src/main/java/com/seugi/network/timetable/di/DataSourceModule.kt
  network/timetable/src/main/java/com/seugi/network/timetable/response/TimetableResponse.kt
  settings.gradle.kts
Labels: Feature

#244 Refactor/Home Screen
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/card/CatSeugiCard.kt
  feature-main/home/src/main/java/com/seugi/home/card/MealCard.kt
  feature-main/home/src/main/java/com/seugi/home/card/ScheduleCard.kt
  feature-main/home/src/main/java/com/seugi/home/card/SchoolCard.kt
  feature-main/home/src/main/java/com/seugi/home/card/TimeScheduleCard.kt
  feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
Labels: Refactor, Feature

#252 Refactor/Permisson api
  data/core/src/main/java/com/seugi/data/core/mapper/ProfileMapper.kt
  data/core/src/main/java/com/seugi/data/core/mapper/WorkspacePermissionMapper.kt
  data/core/src/main/java/com/seugi/data/core/model/ProfileModel.kt
  data/core/src/main/java/com/seugi/data/core/model/WorkspacePermissionModel.kt
  data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
  data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
  feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
  feature-main/notification-edit/src/main/java/com/seugi/notificationedit/NotificationEditScreen.kt
  feature-main/notification-edit/src/main/java/com/seugi/notificationedit/navigation/NotificationEditNavigation.kt
  feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
  feature-main/notification/src/main/java/com/seugi/notification/navigation/NotificationNavigation.kt
  feature-main/profile/src/main/java/com/seugi/profile/model/ProfileUiState.kt
  network/core/src/main/java/com/seugi/network/core/response/ProfileResponse.kt
  network/core/src/main/java/com/seugi/network/core/response/WorkspacePermissionResponse.kt
  network/workspace/src/main/java/com/seugi/network/workspace/WorkspaceDataSource.kt
  network/workspace/src/main/java/com/seugi/network/workspace/datasource/WorkspaceDataSourceImpl.kt
Labels: Refactor

#253 Feature/Set Lazy Column Background
  feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/FirstScreen.kt
  feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/SecondScreen.kt
  feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
Labels: Feature

#248 Feature/Create setting screen
  app/src/main/java/com/seugi/MainActivity.kt
  common/src/main/java/com/seugi/common/utiles/Utiles.kt
  data/member/src/main/java/com/seugi/data/member/MemberRepository.kt
  data/member/src/main/java/com/seugi/data/member/repository/MemberRepositoryImpl.kt
  data/token/src/main/java/com/seugi/data/token/TokenRepository.kt
  data/token/src/main/java/com/seugi/data/token/repository/TokenRepositoryImpl.kt
  data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
  data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/main/src/main/java/com/seugi/main/navigation/MainNavigation.kt
  feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
  feature-main/profile/src/main/java/com/seugi/profile/navigation/ProfileNavigation.kt
  feature-main/setting/build.gradle.kts
  feature-main/setting/src/main/java/com/seugi/setting/SettingScreen.kt
  feature-main/setting/src/main/java/com/seugi/setting/SettingViewModel.kt
  feature-main/setting/src/main/java/com/seugi/setting/model/SettingSideEffect.kt
  feature-main/setting/src/main/java/com/seugi/setting/model/SettingUiState.kt
  feature-main/setting/src/main/java/com/seugi/setting/navigate/SettingNavigate.kt
  settings.gradle.kts
Labels: Feature

#256 Feature/Handle Notification API
  data/notification/src/main/java/com/seugi/data/notification/mapper/NotificationMapper.kt
  data/notification/src/main/java/com/seugi/data/notification/model/NotificationEmojiModel.kt
  feature-main/notification-create/src/main/java/com/seugi/notificationcreate/NotificationCreateScreen.kt
  feature-main/notification-edit/src/main/java/com/seugi/notificationedit/NotificationEditScreen.kt
  feature-main/notification/build.gradle.kts
  feature-main/notification/src/main/java/com/seugi/notification/NotificationScreen.kt
  feature-main/notification/src/main/java/com/seugi/notification/NotificationViewModel.kt
  feature-main/notification/src/main/java/com/seugi/notification/model/NotificationUiState.kt
  gradle/libs.versions.toml
  network/notification/src/main/java/com/seugi/network/notification/response/NotificationEmojiResponse.kt
  settings.gradle.kts
Labels: Feature

#262 Feature/Other Profile Bottom Sheet
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/workspace-detail/build.gradle.kts
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/model/WorkspaceMemberSideEffect.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceMemberNavigation.kt
  ui/build.gradle.kts
  ui/src/main/java/com/seugi/ui/component/OtherProfileBottomSheet.kt
Labels: Feature

#264 Fix/Two Member Repository
  data/member/src/main/java/com/seugi/data/MemberRepository.kt
  data/member/src/main/java/com/seugi/data/mapper/EmailSignInMapper.kt
  data/member/src/main/java/com/seugi/data/member/MemberRepositoryModule.kt
  data/member/src/main/java/com/seugi/data/member/di/MemberRepositoryModule.kt
  data/member/src/main/java/com/seugi/data/model/EmailSignInModel.kt
  data/member/src/main/java/com/seugi/data/repository/MemberRepositoryImpl.kt
Labels: Feature

#257 Feature/Cat Seugi API
  .github/workflows/ci.yml
  data/catseugi/build.gradle.kts
  data/catseugi/src/main/java/com/seugi/data/catseugi/CatSeugiRepository.kt
  data/catseugi/src/main/java/com/seugi/data/catseugi/di/RepositoryModule.kt
  data/catseugi/src/main/java/com/seugi/data/catseugi/repository/CatSeugiRepositoryImpl.kt
  feature-main/chat-seugi/build.gradle.kts
  feature-main/chat-seugi/src/main/java/com/seugi/chatseugi/ChatSeugiScreen.kt
  feature-main/chat-seugi/src/main/java/com/seugi/chatseugi/ChatSeugiViewModel.kt
  feature-main/chat-seugi/src/main/java/com/seugi/chatseugi/model/ChatSeugiUiState.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  gradle.properties
  network/catseugi/build.gradle.kts
  network/catseugi/src/main/java/com/seugi/network/catseugi/CatSeugiDataSource.kt
  network/catseugi/src/main/java/com/seugi/network/catseugi/datasource/CatSeugiDataSourceImpl.kt
  network/catseugi/src/main/java/com/seugi/network/catseugi/di/DataSourceModule.kt
  network/catseugi/src/main/java/com/seugi/network/catseugi/request/CatSeugiRequest.kt
  network/core/build.gradle.kts
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  settings.gradle.kts
Labels: Feature
