Repository apeun-gidaechi/seugi-android, pull requests merged in 2024-08, with the labels that each got.

#182 Feature/Design System Reflection
  designsystem-preview/src/main/java/com/apeun/gidaechi/designsystem/preview/feature/RoomImage.kt
  designsystem/src/main/java/com/seugi/designsystem/component/DatePicker.kt
  designsystem/src/main/java/com/seugi/designsystem/component/Image.kt
  designsystem/src/main/java/com/seugi/designsystem/component/ListItem.kt
  designsystem/src/main/java/com/seugi/designsystem/component/MemberList.kt
  designsystem/src/main/java/com/seugi/designsystem/component/RoundedCircleImage.kt
  designsystem/src/main/java/com/seugi/designsystem/component/SegmentedButton.kt
  designsystem/src/main/java/com/seugi/designsystem/component/TimePicker.kt
  designsystem/src/main/java/com/seugi/designsystem/component/chat/ChatRoom.kt
  designsystem/src/main/java/com/seugi/designsystem/component/modifier/IfModifier.kt
  designsystem/src/main/res/drawable/ic_crown_fill.xml
  designsystem/src/main/res/drawable/ic_expand_left_line.xml
  feature-main/room-create/src/main/java/com/seugi/roomcreate/screen/SecondScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/JoinSuccessScreen.kt
Labels: Feature

#183 Refactor/Chat Detail View
  designsystem/src/main/res/drawable/ic_file_line.xml
  feature-main/chat-datail/build.gradle.kts
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/BackupChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/BackupChatDetailViewModel.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  ui/src/main/java/com/seugi/ui/Extensions.kt
Labels: Refactor, Feature

#184 Refactor/Move Workspace Code And Refactor
  designsystem/src/main/res/drawable/img_check.xml
  designsystem/src/main/res/drawable/img_school.png
  designsystem/src/main/res/drawable/img_student.png
  designsystem/src/main/res/drawable/img_teacher.png
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/workspace/.gitignore
  feature-main/workspace/build.gradle.kts
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/SelectingJobScreen.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/WaitingJoinScreen.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/joinsuccess/JoinSuccessScreen.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/joinsuccess/JoinSuccessViewModel.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/joinsuccess/model/JoinSuccessSideEffect.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/schoolcode/SchoolCodeScreen.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/schoolcode/SchoolCodeViewModel.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/schoolcode/model/SchoolCodeModel.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/navigation/JoinSuccessNavigation.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/navigation/SchoolCodeNavigation.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/navigation/SelectingJobNavigation.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/navigation/WaitingJoinNavigation.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/selectingcode/model/SelectingCodeSideEffect.kt
  feature-onboarding/join/src/main/java/com/seugi/join/navigation/SelectingJobNavigation.kt
  feature-onboarding/login/src/main/java/com/seugi/login/EmailSignInScreen.kt
  feature-onboarding/onabording/src/main/java/com/seugi/onboarding/OnboardingScreen.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  settings.gradle.kts
Labels: Refactor

#187 Feature/Auto Refresh Socket Client
  data/message/build.gradle.kts
  data/message/src/main/java/com/seugi/data/message/MessageRepository.kt
  data/message/src/main/java/com/seugi/data/message/mapper/MessageStompMapper.kt
  data/message/src/main/java/com/seugi/data/message/model/stomp/MessageStompLifecycleModel.kt
  data/message/src/main/java/com/seugi/data/message/repository/MessageRepositoryImpl.kt
  data/token/build.gradle.kts
  data/token/src/main/java/com/seugi/data/token/TokenRepository.kt
  data/token/src/main/java/com/seugi/data/token/repository/TokenRepositoryImpl.kt
  feature-main/chat-datail/build.gradle.kts
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  gradle/libs.versions.toml
  network/core/build.gradle.kts
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/core/src/main/java/com/seugi/network/core/Test.kt
  network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
  network/group-chat/src/main/java/com/seugi/network/groupchat/datasource/GroupChatDataSourceImpl.kt
  network/message/build.gradle.kts
  network/message/src/main/java/com/seugi/network/message/MessageDataSource.kt
  network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
  network/message/src/main/java/com/seugi/network/message/response/stomp/MessageStompLifecycleResponse.kt
  network/notification/src/main/java/com/seugi/network/notification/datasource/NotificationDataSourceImpl.kt
  network/personal-chat/src/main/java/com/apeun/gidaechi/data/personalchat/datasource/PersonalChatDataSourceImpl.kt
  network/profile/src/main/java/com/seugi/network/profile/datasource/ProfileDataSourceImpl.kt
  network/token/.gitignore
  network/token/build.gradle.kts
  network/token/src/main/java/com/seugi/network/token/TokenDatasource.kt
  network/token/src/main/java/com/seugi/network/token/datasource/TokenDatasourceImpl.kt
  network/token/src/main/java/com/seugi/network/token/di/DatasourceModule.kt
  network/workspace/src/main/java/com/seugi/network/workspace/datasource/WorkspaceDataSourceImpl.kt
  settings.gradle.kts
  stomp-client/.gitignore
  stomp-client/build.gradle.kts
  stomp-client/src/main/java/com/seugi/stompclient/HeartBeatTask.java
  stomp-client/src/main/java/com/seugi/stompclient/Stomp.java
  stomp-client/src/main/java/com/seugi/stompclient/StompClient.java
  stomp-client/src/main/java/com/seugi/stompclient/StompException.java
  stomp-client/src/main/java/com/seugi/stompclient/dto/LifecycleEvent.java
  stomp-client/src/main/java/com/seugi/stompclient/dto/StompCommand.java
  stomp-client/src/main/java/com/seugi/stompclient/dto/StompHeader.java
  stomp-client/src/main/java/com/seugi/stompclient/dto/StompMessage.java
  stomp-client/src/main/java/com/seugi/stompclient/pathmatcher/PathMatcher.java
  stomp-client/src/main/java/com/seugi/stompclient/pathmatcher/RabbitPathMatcher.java
  stomp-client/src/main/java/com/seugi/stompclient/pathmatcher/SimplePathMatcher.java
  stomp-client/src/main/java/com/seugi/stompclient/pathmatcher/SubscriptionPathMatcher.java
  stomp-client/src/main/java/com/seugi/stompclient/provider/AbstractConnectionProvider.java
  stomp-client/src/main/java/com/seugi/stompclient/provider/ConnectionProvider.java
  stomp-client/src/main/java/com/seugi/stompclient/provider/OkHttpConnectionProvider.java
  stomp-client/src/main/java/com/seugi/stompclient/provider/WebSocketsConnectionProvider.java
Labels: Refactor, Feature

#189 Feature/Main Manage Workspace
  data/profile/build.gradle.kts
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/ChatDetailViewModel.kt
  feature-main/chat-datail/src/main/java/com/seugi/chatdatail/navigation/ChatDetailNavigation.kt
  feature-main/chat/src/main/java/com/seugi/chat/ChatScreen.kt
  feature-main/chat/src/main/java/com/seugi/chat/ChatViewModel.kt
  feature-main/chat/src/main/java/com/seugi/chat/navigation/ChatNavigation.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
  feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
  feature-main/profile/src/main/java/com/seugi/profile/ProfileScreen.kt
  feature-main/profile/src/main/java/com/seugi/profile/ProfileViewModel.kt
  feature-main/profile/src/main/java/com/seugi/profile/navigation/ProfileNavigation.kt
  feature-main/room/src/main/java/com/seugi/room/RoomScreen.kt
  feature-main/room/src/main/java/com/seugi/room/RoomViewModel.kt
  feature-main/room/src/main/java/com/seugi/room/navigation/RoomNavigation.kt
  network/token/src/main/java/com/seugi/network/token/datasource/TokenDatasourceImpl.kt
Labels: Feature

#191 Feature/Create Workspace Table
  data/workspace/build.gradle.kts
  data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
  data/workspace/src/main/java/com/seugi/data/workspace/mapper/WorkspaceMapper.kt
  data/workspace/src/main/java/com/seugi/data/workspace/model/WorkspaceModel.kt
  data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
  feature-main/home/build.gradle.kts
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/seugi/main/MainViewModel.kt
  local/room/src/main/java/com/seugi/local/room/SeugiDatabase.kt
  local/room/src/main/java/com/seugi/local/room/dao/WorkspaceDao.kt
  local/room/src/main/java/com/seugi/local/room/di/SeugiDaoModule.kt
  local/room/src/main/java/com/seugi/local/room/di/SeugiDatabaseModule.kt
  local/room/src/main/java/com/seugi/local/room/model/WorkspaceEntity.kt
  local/room/src/main/java/com/seugi/local/room/util/SeugiTable.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/workspace/src/main/java/com/seugi/network/workspace/WorkspaceDataSource.kt
  network/workspace/src/main/java/com/seugi/network/workspace/datasource/WorkspaceDataSourceImpl.kt
  network/workspace/src/main/java/com/seugi/network/workspace/response/WorkspaceResponse.kt
Labels: Feature

#193 Feature/Link Workspace To Home
  designsystem-preview/src/main/java/com/apeun/gidaechi/designsystem/preview/feature/Dialog.kt
  designsystem/src/main/java/com/seugi/designsystem/component/Dialog.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
Labels: Feature

#196 Feature/Create Workspace Detail And Member View
  data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
  data/workspace/src/main/java/com/seugi/data/workspace/mapper/WaitWorkspaceMapper.kt
  data/workspace/src/main/java/com/seugi/data/workspace/model/WaitWorkspaceModel.kt
  data/workspace/src/main/java/com/seugi/data/workspace/model/WorkspaceModel.kt
  data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
  designsystem-preview/src/main/java/com/apeun/gidaechi/designsystem/preview/feature/Dropdown.kt
  designsystem/src/main/java/com/seugi/designsystem/component/Dropdown.kt
  designsystem/src/main/java/com/seugi/designsystem/component/MemberList.kt
  designsystem/src/main/java/com/seugi/designsystem/component/RoundedCircleImage.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
  feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/workspace-detail/.gitignore
  feature-main/workspace-detail/build.gradle.kts
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceDetailNavigation.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/joinsuccess/JoinSuccessViewModel.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/schoolcode/SchoolCodeViewModel.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/workspace/src/main/java/com/seugi/network/workspace/WorkspaceDataSource.kt
  network/workspace/src/main/java/com/seugi/network/workspace/datasource/WorkspaceDataSourceImpl.kt
  network/workspace/src/main/java/com/seugi/network/workspace/response/WaitWorkspaceResponse.kt
  settings.gradle.kts
Labels: Feature

#200 Refactor/Date Picker Indicator Offset Logic
  designsystem/src/main/java/com/seugi/designsystem/component/DatePicker.kt
Labels: Refactor

#203 Feature/Create Workspace Member
  data/workspace/build.gradle.kts
  data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
  data/workspace/src/main/java/com/seugi/data/workspace/mapper/WorkspaceMapper.kt
  data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberViewModel.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/model/WorkspaceMemberUiState.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceDetailNavigation.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceMemberNavigation.kt
  local/room/src/main/java/com/seugi/local/room/dao/WorkspaceDao.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
Labels: Feature

#207 Feature/Create Create Workspace
  data/file/.gitignore
  data/file/build.gradle.kts
  data/file/src/main/java/com/seugi/data/file/FileRepository.kt
  data/file/src/main/java/com/seugi/data/file/di/RepositoryModule.kt
  data/file/src/main/java/com/seugi/data/file/mapper/FileMapper.kt
  data/file/src/main/java/com/seugi/data/file/model/FileModel.kt
  data/file/src/main/java/com/seugi/data/file/model/FileType.kt
  data/file/src/main/java/com/seugi/data/file/repository/FileRepositoryImpl.kt
  data/workspace/build.gradle.kts
  data/workspace/src/main/java/com/seugi/data/workspace/WorkspaceRepository.kt
  data/workspace/src/main/java/com/seugi/data/workspace/repository/WorkspaceRepositoryImpl.kt
  designsystem/src/main/java/com/seugi/designsystem/component/Dropdown.kt
  designsystem/src/main/java/com/seugi/designsystem/component/SegmentedButton.kt
  designsystem/src/main/java/com/seugi/designsystem/component/textfield/CodeTextField.kt
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/navigation/HomeNavigation.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/seugi/main/MainScreen.kt
  feature-main/workspace-create/.gitignore
  feature-main/workspace-create/build.gradle.kts
  feature-main/workspace-create/src/main/java/com/seugi/workspacecreate/WorkspaceCreateScreen.kt
  feature-main/workspace-create/src/main/java/com/seugi/workspacecreate/WorkspaceCreateViewModel.kt
  feature-main/workspace-create/src/main/java/com/seugi/workspacecreate/model/WorkspaceCreateSideEffect.kt
  feature-main/workspace-create/src/main/java/com/seugi/workspacecreate/navigation/WorkspaceCreateNacigation.kt
  feature-main/workspace-detail/build.gradle.kts
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
  feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/navigation/WorkspaceDetailNavigation.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/SelectingJobScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/emailverification/EmailVerificationScreen.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/file/.gitignore
  network/file/build.gradle.kts
  network/file/src/main/java/com/seugi/file/FileDataSource.kt
  network/file/src/main/java/com/seugi/file/datasource/FileDataSourceImpl.kt
  network/file/src/main/java/com/seugi/file/di/FileSourceModule.kt
  network/file/src/main/java/com/seugi/file/request/FileRequest.kt
  network/file/src/main/java/com/seugi/file/response/FileResponse.kt
  network/message/src/main/java/com/seugi/network/message/datasource/MessageDataSourceImpl.kt
  network/workspace/src/main/java/com/seugi/network/workspace/WorkspaceDataSource.kt
  network/workspace/src/main/java/com/seugi/network/workspace/datasource/WorkspaceDataSourceImpl.kt
  network/workspace/src/main/java/com/seugi/network/workspace/request/CreateWorkspaceRequest.kt
  settings.gradle.kts
Labels: Feature

#212 refactor: Error Text Padding
  feature-onboarding/join/src/main/java/com/seugi/join/feature/EmailSignUpScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/OAuthSignUpScreen.kt
  feature-onboarding/login/src/main/java/com/seugi/login/EmailSignInScreen.kt
Labels: Refactor

#213 Fix/Null Image Bug
  feature-main/workspace/src/main/java/com/seugi/workspace/feature/joinsuccess/JoinSuccessScreen.kt
  feature-main/workspace/src/main/java/com/seugi/workspace/navigation/JoinSuccessNavigation.kt
Labels: Bug

#214 Feature/Meal Remote, Local feature
  common/build.gradle.kts
  common/src/main/java/com/seugi/common/utiles/Extension.kt
  data/meal/build.gradle.kts
  data/meal/src/main/java/com/seugi/data/meal/MealRepository.kt
  data/meal/src/main/java/com/seugi/data/meal/di/RepositoryModule.kt
  data/meal/src/main/java/com/seugi/data/meal/mapper/MealMapper.kt
  data/meal/src/main/java/com/seugi/data/meal/repository/MealRepositoryImpl.kt
  data/meal/src/main/java/com/seugi/data/meal/response/MealModel.kt
  data/meal/src/main/java/com/seugi/data/meal/response/MealType.kt
  feature-main/home/build.gradle.kts
  feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
  local/room/src/main/java/com/seugi/local/room/SeugiDatabase.kt
  local/room/src/main/java/com/seugi/local/room/dao/MealDao.kt
  local/room/src/main/java/com/seugi/local/room/di/SeugiDaoModule.kt
  local/room/src/main/java/com/seugi/local/room/model/MealEntity.kt
  local/room/src/main/java/com/seugi/local/room/util/SeugiTable.kt
  network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
  network/meal/build.gradle.kts
  network/meal/src/main/java/com/seugi/network/meal/MealDataSource.kt
  network/meal/src/main/java/com/seugi/network/meal/datasource/MealDataSourceImpl.kt
  network/meal/src/main/java/com/seugi/network/meal/di/DataSourceModule.kt
  network/meal/src/main/java/com/seugi/network/meal/response/MealResponse.kt
  settings.gradle.kts
Labels: Feature

#216 Feature/Is Save Token Path Set Main
  app/build.gradle.kts
  app/src/main/java/com/seugi/MainActivity.kt
  app/src/main/java/com/seugi/MainViewModel.kt
  app/src/main/res/drawable/ic_seugi.png
Labels: Feature

#220 Feature/Create Start Animation
  feature-onboarding/start/src/main/java/com/seugi/start/StartScreen.kt
Labels: Feature

#222 Feature/Edit Launch Screen Time
  app/src/main/java/com/seugi/MainActivity.kt
Labels: Feature

#226 Feature/Token Refresh
  app/src/main/java/com/seugi/di/ActivityStarterModule.kt
  app/src/main/java/com/seugi/starter/SeugiActivityStarterImpl.kt
  common/src/main/java/com/seugi/common/utiles/SeugiActivityStarter.kt
  feature-onboarding/login/src/main/java/com/seugi/login/EmailSignInViewModel.kt
  network/core/src/main/java/com/seugi/network/core/di/NetworkModule.kt
Labels: Feature
