Repository apeun-gidaechi/seugi-android, pull requests merged in 2024-07, with the labels that each got.

#141 Feature/Home Screen Calendar Color Edit
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
Labels: Feature

#142 Feature/Chat Detail UI
  app/src/main/AndroidManifest.xml
  data/core/src/main/java/com/apeun/gidaechi/data/core/model/ChatRoomModel.kt
  data/message/src/main/java/com/apeun/gidaechi/message/mapper/MessageSubMapper.kt
  data/message/src/main/java/com/apeun/gidaechi/message/model/sub/MessageSubModel.kt
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/chat/ChatItem.kt
  feature-main/chat-datail/src/main/java/com/apeun/gidaechi/chatdatail/ChatDetailScreen.kt
  feature-main/chat-datail/src/main/java/com/apeun/gidaechi/chatdatail/ChatDetailViewModel.kt
  feature-main/chat-datail/src/main/java/com/apeun/gidaechi/chatdatail/model/ChatDetailUiState.kt
  feature-main/chat/src/main/java/com/apeun/gidaechi/chat/ChatScreen.kt
  feature-main/room/src/main/java/com/apeun/gidaechi/room/RoomScreen.kt
  network/core/src/main/java/com/apeun/gidaechi/network/core/Test.kt
  network/core/src/main/java/com/apeun/gidaechi/network/core/response/ChatRoomResponse.kt
  network/message/src/main/java/com/apeun/gidaechi/network/message/response/sub/MessageSubResponse.kt
Labels: Feature

#144 Feature/Add Google, Apple Icon
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/OAuthButton.kt
  feature-onboarding/start/src/main/java/com/apeun/gidaechi/StartScreen.kt
  feature-onboarding/start/src/main/res/drawable/ic_apple.xml
  feature-onboarding/start/src/main/res/drawable/ic_google.xml
Labels: Feature

#145 Feature/Create Local Room Module
  local/room/.gitignore
  local/room/build.gradle.kts
  local/room/src/main/java/com/apeun/gidaechi/local/room/SeugiDatabase.kt
  local/room/src/main/java/com/apeun/gidaechi/local/room/base/BaseDao.kt
  local/room/src/main/java/com/apeun/gidaechi/local/room/dao/TokenDao.kt
  local/room/src/main/java/com/apeun/gidaechi/local/room/di/SeugiDaoModule.kt
  local/room/src/main/java/com/apeun/gidaechi/local/room/di/SeugiDatabaseModule.kt
  local/room/src/main/java/com/apeun/gidaechi/local/room/model/TokenEntity.kt
  local/room/src/main/java/com/apeun/gidaechi/local/room/util/SeugiTable.kt
  settings.gradle.kts
Labels: Feature

#150 Feature/Home Screen Not Found
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/LoadingDotsIndicator.kt
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/apeun/gidaechi/home/model/HomeUiState.kt
Labels: Feature

#154 Feature/Edit Navigation
  app/src/main/java/com/apeun/gidaechi/seugi/MainActivity.kt
  feature-main/main/src/main/java/com/apeun/gidaechi/main/MainScreen.kt
  feature-main/main/src/main/java/com/apeun/gidaechi/main/navigation/MainNavigation.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/EmailVerificationScreen.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/navigation/EmailVerificationNavigation.kt
  feature-onboarding/onabording/src/main/java/com/apeun/gidaechi/OnboardingScreen.kt
Labels: Feature

#157 Feature/Chat Seugi Screen
  .idea/misc.xml
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/chat/ChatItem.kt
  feature-main/chat-seugi/.gitignore
  feature-main/chat-seugi/build.gradle.kts
  feature-main/chat-seugi/consumer-rules.pro
  feature-main/chat-seugi/proguard-rules.pro
  feature-main/chat-seugi/src/main/AndroidManifest.xml
  feature-main/chat-seugi/src/main/java/com/apeun/gidaechi/chatseugi/ChatSeugiScreen.kt
  feature-main/chat-seugi/src/main/java/com/apeun/gidaechi/chatseugi/ChatSeugiViewModel.kt
  feature-main/chat-seugi/src/main/java/com/apeun/gidaechi/chatseugi/model/ChatSeugiUiState.kt
  feature-main/chat-seugi/src/main/java/com/apeun/gidaechi/chatseugi/navigation/ChatSeugiNavigation.kt
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/apeun/gidaechi/home/navigation/HomeNavigation.kt
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/apeun/gidaechi/main/MainScreen.kt
  settings.gradle.kts
Labels: Feature

#158 Feature/Add Dummy Data
  designsystem/src/main/res/drawable/ic_apple.png
  designsystem/src/main/res/drawable/ic_morning.png
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
Labels: Feature

#162 Feature/Home School Change
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeViewModel.kt
  feature-main/home/src/main/java/com/apeun/gidaechi/home/model/HomeUiState.kt
Labels: Feature

#164 Feature/Chat Detail Join Left View
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/BottomNavigation.kt
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/chat/ChatItem.kt
  feature-main/chat-datail/src/main/java/com/apeun/gidaechi/chatdatail/ChatDetailScreen.kt
  feature-main/chat/src/main/java/com/apeun/gidaechi/chat/ChatViewModel.kt
  feature-main/room/src/main/java/com/apeun/gidaechi/room/RoomViewModel.kt
Labels: Feature

#166 Feature/Notice Remote
  common/src/main/java/com/apeun/gidaechi/common/utiles/Extension.kt
  data/notice/.gitignore
  data/notice/build.gradle.kts
  data/notice/consumer-rules.pro
  data/notice/proguard-rules.pro
  data/notice/src/main/AndroidManifest.xml
  data/notice/src/main/java/com/apeun/gidaechi/data/notice/NoticeRepository.kt
  data/notice/src/main/java/com/apeun/gidaechi/data/notice/di/RepositoryModule.kt
  data/notice/src/main/java/com/apeun/gidaechi/data/notice/mapper/NoticeMapper.kt
  data/notice/src/main/java/com/apeun/gidaechi/data/notice/model/NoticeModel.kt
  data/notice/src/main/java/com/apeun/gidaechi/data/notice/repository/NoticeRepositoryImpl.kt
  feature-main/notification/build.gradle.kts
  feature-main/notification/src/main/java/com/apeun/gidaechi/notification/NotificationScreen.kt
  feature-main/notification/src/main/java/com/apeun/gidaechi/notification/NotificationViewModel.kt
  feature-main/notification/src/main/java/com/apeun/gidaechi/notification/model/NotificationUiState.kt
  network/core/src/main/java/com/apeun/gidaechi/network/core/SeugiUrl.kt
  network/notice/.gitignore
  network/notice/build.gradle.kts
  network/notice/consumer-rules.pro
  network/notice/proguard-rules.pro
  network/notice/src/main/AndroidManifest.xml
  network/notice/src/main/java/com/apeun/gidaechi/network/notice/NoticeDataSource.kt
  network/notice/src/main/java/com/apeun/gidaechi/network/notice/datasource/NoticeDataSourceImpl.kt
  network/notice/src/main/java/com/apeun/gidaechi/network/notice/di/DataSourceModule.kt
  network/notice/src/main/java/com/apeun/gidaechi/network/notice/response/NoticeResponse.kt
  settings.gradle.kts
Labels: Feature

#168 Refactor/Edit School Schedule D-day
  data/message/src/main/java/com/apeun/gidaechi/message/model/room/MessageRoomModel.kt
  feature-main/chat-seugi/src/main/java/com/apeun/gidaechi/chatseugi/ChatSeugiViewModel.kt
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeViewModel.kt
  network/message/src/main/java/com/apeun/gidaechi/network/message/response/room/MessageRoomResponse.kt
Labels: Refactor

#171 Feature/Chat Room Search
  feature-main/chat/src/main/java/com/apeun/gidaechi/chat/ChatScreen.kt
  feature-main/chat/src/main/java/com/apeun/gidaechi/chat/ChatViewModel.kt
  feature-main/chat/src/main/java/com/apeun/gidaechi/chat/model/ChatUiState.kt
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
  feature-main/room/src/main/java/com/apeun/gidaechi/room/RoomScreen.kt
  feature-main/room/src/main/java/com/apeun/gidaechi/room/RoomViewModel.kt
  feature-main/room/src/main/java/com/apeun/gidaechi/room/model/RoomUiState.kt
Labels: Feature

#173 Feature/Create Interceptor
  data/token/build.gradle.kts
  network/core/build.gradle.kts
  network/core/src/main/java/com/apeun/gidaechi/network/core/di/NetworkModule.kt
  network/core/src/main/java/com/apeun/gidaechi/network/core/utiles/Extension.kt
Labels: Feature

#177 Fix/Side Effect
  feature-onboarding/join/build.gradle.kts
  feature-onboarding/join/src/main/java/com/seugi/join/EmailVerificationScreen.kt
Labels: Bug

#180 Refactor/Edit Package
  feature-onboarding/join/src/main/java/com/seugi/join/feature/EmailSignUpScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/JoinSuccessScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/OAuthSignUpScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/WaitingJoinScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/emailverification/EmailVerificationScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/emailverification/EmailVerificationViewModel.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/emailverification/model/EmailVerificationSideEffect.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/schoolcode/SchoolCodeScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/schoolcode/SchoolCodeViewModel.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/schoolcode/model/SchoolCodeModel.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/selectingcode/SelectingCodeViewModel.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/selectingcode/SelectingJobScreen.kt
  feature-onboarding/join/src/main/java/com/seugi/join/feature/selectingcode/model/SelectingCodeSideEffect.kt
  feature-onboarding/join/src/main/java/com/seugi/join/navigation/EmailSignUpNavigation.kt
  feature-onboarding/join/src/main/java/com/seugi/join/navigation/EmailVerificationNavigation.kt
  feature-onboarding/join/src/main/java/com/seugi/join/navigation/JoinSuccessNavigation.kt
  feature-onboarding/join/src/main/java/com/seugi/join/navigation/OAuthSingUpNavigation.kt
  feature-onboarding/join/src/main/java/com/seugi/join/navigation/SchoolCodeNavigation.kt
  feature-onboarding/join/src/main/java/com/seugi/join/navigation/SelectingJobNavigation.kt
  feature-onboarding/join/src/main/java/com/seugi/join/navigation/WaitingJoinNavigation.kt
Labels: Refactor
