Repository apeun-gidaechi/seugi-android, pull requests merged in 2024-06, with the labels that each got.

#98 Feature/Email SignIn
  .github/workflows/ci.yml
  .gitignore
  app/src/main/java/com/apeun/gidaechi/seugi/MainActivity.kt
  data/email-sign-in/.gitignore
  data/email-sign-in/build.gradle.kts
  data/email-sign-in/consumer-rules.pro
  data/email-sign-in/proguard-rules.pro
  data/email-sign-in/src/main/AndroidManifest.xml
  data/email-sign-in/src/main/java/com/apeun/gidaechi/data/EmailSignInRepository.kt
  data/email-sign-in/src/main/java/com/apeun/gidaechi/data/di/EmailSignInRepositoryModule.kt
  data/email-sign-in/src/main/java/com/apeun/gidaechi/data/mapper/EmailSignInMapper.kt
  data/email-sign-in/src/main/java/com/apeun/gidaechi/data/model/EmailSignInModel.kt
  data/email-sign-in/src/main/java/com/apeun/gidaechi/data/repository/EmailSignInRepositoryImpl.kt
  designsystem-preview/src/main/java/com/apeun/gidaechi/designsystem/preview/feature/ChatItem.kt
  designsystem-preview/src/main/java/com/apeun/gidaechi/designsystem/preview/feature/ChatList.kt
  designsystem-preview/src/main/java/com/apeun/gidaechi/designsystem/preview/feature/TopBar.kt
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Button.kt
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/TopBar.kt
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/chat/ChatItem.kt
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/chat/ChatList.kt
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/textfield/ChatTextField.kt
  feature-main/chat-datail/src/main/java/com/apeun/gidaechi/chatdatail/ChatDetailScreen.kt
  feature-onboarding/join/build.gradle.kts
  feature-onboarding/login/build.gradle.kts
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/EmailSignInScreen.kt
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/EmailSignInVIewModel.kt
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/model/EmailSignInSideEffect.kt
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/model/EmailSignInState.kt
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/navigation/EmailSignInNavigation.kt
  feature-onboarding/onabording/src/main/java/com/apeun/gidaechi/OnboardingScreen.kt
  feature-onboarding/onabording/src/main/java/com/apeun/gidaechi/navigation/OnboardingNavigation.kt
  feature-onboarding/start/src/main/java/com/apeun/gidaechi/navigation/StartNavigation.kt
  network/core/build.gradle.kts
  network/core/src/main/java/com/apeun/gidaechi/network/core/SeugiUrl.kt
  network/core/src/main/java/com/apeun/gidaechi/network/core/response/BaseResponse.kt
  network/sign-in/.gitignore
  network/sign-in/build.gradle.kts
  network/sign-in/consumer-rules.pro
  network/sign-in/proguard-rules.pro
  network/sign-in/src/main/AndroidManifest.xml
  network/sign-in/src/main/java/com/apeun/gidaechi/network/EmailSignInDatasource.kt
  network/sign-in/src/main/java/com/apeun/gidaechi/network/datasource/EmailSignInDatasourceImpl.kt
  network/sign-in/src/main/java/com/apeun/gidaechi/network/di/EmailSignInDataourceModule.kt
  network/sign-in/src/main/java/com/apeun/gidaechi/network/request/EmailSignInRequest.kt
  network/sign-in/src/main/java/com/apeun/gidaechi/network/response/EmailSignInResponse.kt
  settings.gradle.kts
Labels: Feature

#114 Feature/Create Pull Request Templete
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs

#121 Feature/Create School Join
  data/workspace/.gitignore
  data/workspace/build.gradle.kts
  data/workspace/consumer-rules.pro
  data/workspace/proguard-rules.pro
  data/workspace/src/main/AndroidManifest.xml
  data/workspace/src/main/java/com/apeun/gidaechi/data/workspace/WorkspaceRepository.kt
  data/workspace/src/main/java/com/apeun/gidaechi/data/workspace/di/RepositoryModule.kt
  data/workspace/src/main/java/com/apeun/gidaechi/data/workspace/mapper/CheckWorkspaceMapper.kt
  data/workspace/src/main/java/com/apeun/gidaechi/data/workspace/model/CheckWorkspaceModel.kt
  data/workspace/src/main/java/com/apeun/gidaechi/data/workspace/repository/WorkspaceRepositoryImpl.kt
  feature-onboarding/join/build.gradle.kts
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/EmailVerificationScreen.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/JoinSuccessScreen.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/SchoolCodeScreen.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/SelectingJobScreen.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/model/SchoolCodeModel.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/model/SelectingCodeSideEffect.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/navigation/JoinSuccessNavigation.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/navigation/SchoolCodeNavigation.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/navigation/SelectingJobNavigation.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/viewModel/SchoolCodeViewModel.kt
  feature-onboarding/join/src/main/java/com/apeun/gidaechi/viewModel/SelectingCodeViewModel.kt
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/EmailSignInScreen.kt
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/EmailSignInViewModel.kt
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/navigation/EmailSignInNavigation.kt
  feature-onboarding/onabording/src/main/java/com/apeun/gidaechi/OnboardingScreen.kt
  feature-onboarding/start/src/main/java/com/apeun/gidaechi/navigation/StartNavigation.kt
  network/core/src/main/java/com/apeun/gidaechi/network/core/SeugiUrl.kt
  network/workspace/.gitignore
  network/workspace/build.gradle.kts
  network/workspace/consumer-rules.pro
  network/workspace/proguard-rules.pro
  network/workspace/src/main/AndroidManifest.xml
  network/workspace/src/main/java/com/apeun/gidaechi/network/workspace/WorkspaceDatasource.kt
  network/workspace/src/main/java/com/apeun/gidaechi/network/workspace/datasource/WorkspaceDatasourceImpl.kt
  network/workspace/src/main/java/com/apeun/gidaechi/network/workspace/di/WorkspaceModule.kt
  network/workspace/src/main/java/com/apeun/gidaechi/network/workspace/request/WorkspaceApplication.kt
  network/workspace/src/main/java/com/apeun/gidaechi/network/workspace/response/CheckWorkspaceResponse.kt
  settings.gradle.kts
Labels: Feature

#126 Feature/Home Screen View
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/animation/ButtonClick.kt
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/modifier/BrushDrawModifier.kt
  designsystem/src/main/res/drawable/ic_apple.png
  designsystem/src/main/res/drawable/ic_book_fill.xml
  designsystem/src/main/res/drawable/ic_calendar_line.xml
  designsystem/src/main/res/drawable/ic_chicken.png
  designsystem/src/main/res/drawable/ic_taco.png
  designsystem/src/main/res/drawable/ic_utensils_line.xml
  feature-main/home/src/main/java/com/apeun/gidaechi/home/HomeScreen.kt
Labels: Feature

#128 Feature/Notification Screen View
  designsystem/src/main/res/drawable/ic_add_emoji.xml
  designsystem/src/main/res/drawable/ic_detail_vertical_line.xml
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/apeun/gidaechi/main/MainScreen.kt
  feature-main/notification/.gitignore
  feature-main/notification/build.gradle.kts
  feature-main/notification/src/main/java/com/apeun/gidaechi/notification/NotificationScreen.kt
  feature-main/notification/src/main/java/com/apeun/gidaechi/notification/navigation/NotificationNavigation.kt
  settings.gradle.kts
  ui/src/main/java/com/apeun/gidaechi/ui/Utiles.kt
Labels: Feature

#130 Feature/Profile Screen
  designsystem/src/main/res/drawable/ic_write_line.xml
  feature-main/main/build.gradle.kts
  feature-main/main/src/main/java/com/apeun/gidaechi/main/MainScreen.kt
  feature-main/profile/.gitignore
  feature-main/profile/build.gradle.kts
  feature-main/profile/src/main/java/com/apeun/gidaechi/profile/ProfileScreen.kt
  feature-main/profile/src/main/java/com/apeun/gidaechi/profile/ProfileViewModel.kt
  feature-main/profile/src/main/java/com/apeun/gidaechi/profile/model/ProfileUiState.kt
  feature-main/profile/src/main/java/com/apeun/gidaechi/profile/navigation/ProfileNavigation.kt
  settings.gradle.kts
Labels: Feature

#134 Feature/Add Image Border
  designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/RoundedCircleImage.kt
Labels: Feature

#133 Feature/Create Login To Mian
  app/src/main/java/com/apeun/gidaechi/seugi/MainActivity.kt
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/EmailSignInScreen.kt
  feature-onboarding/login/src/main/java/com/apeun/gidaechi/login/navigation/EmailSignInNavigation.kt
  feature-onboarding/onabording/src/main/java/com/apeun/gidaechi/OnboardingScreen.kt
Labels: Feature

#138 Feature/Fix Navigation Bug
  feature-main/main/src/main/java/com/apeun/gidaechi/main/MainScreen.kt
Labels: Bug

#137 Refactor/Data Layer Model
  data/core/src/main/java/com/apeun/gidaechi/data/core/mapper/ChatRoomMapper.kt
  data/core/src/main/java/com/apeun/gidaechi/data/core/model/ChatRoomModel.kt
  data/message/src/main/java/com/apeun/gidaechi/message/mapper/MessageMapper.kt
  data/message/src/main/java/com/apeun/gidaechi/message/mapper/MessageRoomMapper.kt
  data/message/src/main/java/com/apeun/gidaechi/message/mapper/MessageSubMapper.kt
  data/message/src/main/java/com/apeun/gidaechi/message/model/message/MessageEmojiModel.kt
  data/message/src/main/java/com/apeun/gidaechi/message/model/message/MessageLoadModel.kt
  data/message/src/main/java/com/apeun/gidaechi/message/model/message/MessageMessageDeleteModel.kt
  data/message/src/main/java/com/apeun/gidaechi/message/model/message/MessageMessageModel.kt
  data/message/src/main/java/com/apeun/gidaechi/message/model/room/MessageRoomModel.kt
  data/message/src/main/java/com/apeun/gidaechi/message/model/sub/MessageSubModel.kt
Labels: Refactor
